

CREATE TABLE IF NOT EXISTS `BOM_ADMIN_TB` (
  `IDX` INT(9) NOT NULL AUTO_INCREMENT,
  `ADMIN_STATUS` enum('Y','N') NOT NULL DEFAULT 'Y',
  `ADMIN_ID` VARCHAR(20) NOT NULL DEFAULT 'no_id',
  `ADMIN_PASS` VARCHAR(20) DEFAULT NULL,
  `ADMIN_NAME` VARCHAR(50) DEFAULT NULL,
  `ADMIN_PHONE` VARCHAR(20) NOT NULL DEFAULT '02--',
  `ADMIN_MOBILE` VARCHAR(20) NOT NULL DEFAULT '010--',
  `ADMIN_EMAIL` VARCHAR(250) NOT NULL DEFAULT '@',
  `ADMIN_GRADE` VARCHAR(20) NOT NULL DEFAULT 'NNNNNNNNNNNNNNNNNNNN',
  `ADMIN_HIT` INT(11) NOT NULL DEFAULT '0',
  `ADMIN_CMT` TEXT,
  `REG_DATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_DATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`IDX`)
) ENGINE=MyISAM ;

CREATE TABLE IF NOT EXISTS `BOM_CATEGORY_TB` (
  `IDX` INT(9) NOT NULL AUTO_INCREMENT,
  `CTG_P_CODE` VARCHAR(20) NOT NULL DEFAULT '',
  `CTG_CODE_TYPE` VARCHAR(2) NOT NULL DEFAULT '',
  `CTG_CODE` VARCHAR(20) NOT NULL,
  `CTG_NAME` VARCHAR(20) DEFAULT NULL,
  `CTG_DESC` VARCHAR(50) DEFAULT NULL,
  `FROM_DATE` DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TO_DATE` DATETIME NOT NULL DEFAULT '9999-12-31 00:00:00',
  `REG_DATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_DATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`IDX`)
) ENGINE=MyISAM ;


