

CREATE TABLE IF NOT EXISTS `BOM_ADMIN_TB` (
  `IDX` INT(9) NOT NULL AUTO_INCREMENT,
  `ADMIN_STATUS` enum('Y','N') NOT NULL DEFAULT 'Y',
  `ADMIN_ID` VARCHAR(20) NOT NULL DEFAULT 'no_id',
  `ADMIN_PASS` VARCHAR(20) DEFAULT NULL,
  `ADMIN_NAME` VARCHAR(50) DEFAULT NULL,
  `ADMIN_PHONE` VARCHAR(20) NOT NULL DEFAULT '02--',
  `ADMIN_MOBILE` VARCHAR(20) NOT NULL DEFAULT '010--',
  `ADMIN_EMAIL` VARCHAR(250) NOT NULL DEFAULT '@',
  `ADMIN_GRADE` VARCHAR(20) NOT NULL DEFAULT 'NNNNNNNNNNNNNNNNNNNN',
  `ADMIN_HIT` INT(11) NOT NULL DEFAULT '0',
  `ADMIN_CMT` TEXT,
  `REG_DATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_DATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ADMIN_ID`)
) ENGINE=MyISAM ;

CREATE TABLE IF NOT EXISTS `BOM_CATEGORY_TB` (
  `IDX` INT(9) NOT NULL AUTO_INCREMENT,
  `CTG_P_CODE` VARCHAR(20) NOT NULL DEFAULT '',
  `CTG_CODE_TYPE` VARCHAR(2) NOT NULL DEFAULT '',
  `CTG_CODE` VARCHAR(20) NOT NULL,
  `CTG_NAME` VARCHAR(20) DEFAULT NULL,
  `CTG_DESC` VARCHAR(50) DEFAULT NULL,
  `FROM_DATE` DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
  `TO_DATE` DATETIME NOT NULL DEFAULT '9999-12-31 00:00:00',
  `REG_DATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_DATE` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`CTG_CODE`)
) ENGINE=MyISAM ;


[상품TBL]
	IDX
	상품코드(PK)
	상품명
	상품설명
	상품HTML
	카테고리대분류
	카테고리중분류
	카테고리소분류
	
[고객TBL]	
	IDX
	고객ID(PK)
	고객명
	
	
[고객접촉정보TBL]
	IDX
	고객ID(PK)(FK)
	접촉정보번호(PK)
	접촉정보구분코드 - 집,회사,기타
	접촉정보명 - 기타일 경우 입력
	우편번호1
	우편번호2
	주소
	주소상세
	핸드폰번호1
	핸드폰번호2
	핸드폰번호3
	전화번호1
	전화번호2
	전화번호3
PRIMARY KEY (`고객ID`, `접촉정보번호`)

[주문TBL]
	IDX
	주문번호(PK)
	고객ID(FK)
	접촉정보번호(FK)

[주문/상품]
	IDX
	주문ID(FK)
	상품ID(FK)

	